todo: spinningcube_withlight_SKEL

spinningcube_withlight_SKEL: spinningcube_withlight_SKEL.cpp
	g++ -o spinningcube_withlight spinningcube_withlight_SKEL.cpp -lGL -lGLEW -lglfw

clean:
	rm -f *.o *~

cleanall: clean
	rm -f spinningcube_withlight